apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGODB_URL: 4oCTbiDigJxtb25nb2RiOi8vMTAuMTI4LjAuNDU6MjcwMTcvZ2ViZXlhX21vb2Q/cmVwbGljYVNldD1yczDigJ0K


 kubectl create -f mongo-secrets-production.yaml -n  production --validate=false
