apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: sample-service
    role: sample
